name: Spam Issues Check
on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  spam-issues-check:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - name: Check for keywords
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/workflows/spam-issues-check.js')
            await script({github, context})
          github-token: ${{ secrets.GITHUB_TOKEN }}
